rules = [
  OrganizeImports
]

OrganizeImports {
  blankLines = Manual
  groupedImports = Merge
  groups = [
    "re:java\\."
    "re:javax\\."
    "scala."
    "---"
    "*"
  ]
  importsOrder = AsciiCaseInsensitive
  removeUnused = true
  targetDialect = Scala3
}
