version = "3.11.1"
runner.dialect = scala3
maxColumn = 100
align.tokens = [
  { code = "<-", owner = "Enumerator.Generator" },
  { code = "=" }
]
align.tokenCategory {
  Equals = Assign
  LeftArrow = Assign
}
align.arrowEnumeratorGenerator = true

assumeStandardLibraryStripMargin = true

rewrite.rules = [SortModifiers, Imports]
rewrite.imports.sort = ascii
rewrite.trailingCommas.style = always
rewrite.scala3.convertToNewSyntax = true
